openapi: 3.0.3

info:
  title: Pinnacle Api Documentation
  description: >
    Pinnacle Teleservices Pvt. Ltd. offers digital communication solutions,
    focusing on automated, omnichannel customer engagement through services
    like WhatsApp Business API, Google RCS, bulk SMS, IVR, and AI-powered
    chatbots. It enables businesses to build customer relationships via
    personalized messaging, promotions, and customer support with direct
    telecom connectivity for reliability and tracking.
  version: 1.0.0

servers:
  - url: https://api.yourdomain.com

security:
  - ApiKeyAuth: []

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: apikey

  schemas:

    ApiResponse:
      type: object
      properties:
        status:
          type: string
        code:
          type: integer
        data:
          type: object

    Image:
      type: object
      properties:
        url:
          type: string
        type:
          type: string
        key:
          type: string
          
    Suggestion:
      type: object
      properties:
        typeOfAction:
          type: string
          enum: [reply, url_action, dialer_action]
        suggestionText:
          type: string
        urlAction:
          type: string
        phoneNumberToDial:
          type: object
          properties:
            countryCode:
              type: string
            number:
              type: string

    SMSFallback:
      type: object
      properties:
        senderId:
          type: string
        messageType:
          type: string
          enum: [TXT, UNI]
        dltEntityId:
          type: string
        dltTempId:
          type: string
        message:
          type: string

    TextMessageDetails:
      type: object
      properties:
        messageContent:
          type: string
        suggestionsList:
          type: array
          items:
            $ref: '#/components/schemas/Suggestion'

    RichCard:
      type: object
      properties:
        cardOrientation:
          type: string
          enum: [HORIZONTAL, VERTICAL]
        cardAlignment:
          type: string
          enum: [LEFT, RIGHT]
        mediaHeight:
          type: string
          enum: [SHORT_HEIGHT, MEDIUM_HEIGHT]
        cardTitle:
          type: string
        cardDescription:
          type: string
        mediaType:
          type: string
          enum: [image, video]
        media:
          $ref: '#/components/schemas/Image'
        thumbnail:
          $ref: '#/components/schemas/Image'
        suggestionsList:
          type: array
          items:
            $ref: '#/components/schemas/Suggestion'

    CarouselCard:
      type: object
      properties:
        cardId:
          type: string
        cardTitle:
          type: string
        cardDescription:
          type: string
        mediaType:
          type: string
          enum: [image, video]
        cardMedia:
          $ref: '#/components/schemas/Image'
        cardThumbnail:
          $ref: '#/components/schemas/Image'
        suggestionsList:
          type: array
          items:
            $ref: '#/components/schemas/Suggestion'

    Carousel:
      type: object
      properties:
        cardWidth:
          type: string
          enum: [SMALL_WIDTH, MEDIUM_WIDTH]
        mediaHeight:
          type: string
          enum: [SHORT_HEIGHT, MEDIUM_HEIGHT]
        cardsList:
          type: array
          items:
            $ref: '#/components/schemas/CarouselCard'

    Template:
      type: object
      properties:
        _id:
          type: string
        botId:
          type: string
        orgId:
          type: string
        botMessageType:
          type: string
          enum: [PROMOTIONAL, TRANSACTIONAL, OTP]
        templateName:
          type: string
        templateType:
          type: string
          enum: [text_message, rich_card, carousel]
        status:
          type: string
          enum: [pending, approved, rejected]
        isSMSFallbackRequired:
          type: boolean
        smsFallbackTemplateDetails:
          $ref: '#/components/schemas/SMSFallback'
        textMessageDetails:
          $ref: '#/components/schemas/TextMessageDetails'
        richCardStandAloneDetails:
          $ref: '#/components/schemas/RichCard'
        richCardCarouselDetails:
          $ref: '#/components/schemas/Carousel'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

paths:

  /v1/get-all-launched-bots-by-orgId:
    get:
      summary: Get launched bots by orgId
      responses:
        '200':
          description: Launched bots fetched successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'

  /v1/get-bot-details/{botId}:
    get:
      summary: Get bot details by botId
      parameters:
        - name: botId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Bot details fetched
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'

  /v1/create-template:
    post:
      summary: Create Template (Text / Rich Card / Carousel)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Template'
      responses:
        '201':
          description: Template created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'

  /v1/update-template:
    post:
      summary: Update Template
      parameters:
        - name: templateId
          in: header
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Template'
      responses:
        '200':
          description: Template updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'

  /v1/get-all-templates-by-botid:
    get:
      summary: Get templates by botId
      parameters:
        - name: botId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Templates fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Template'

  /v1/get-template-status/{botId}/{templateName}:
    get:
      summary: Get template status
      parameters:
        - name: botId
          in: path
          required: true
          schema:
            type: string
        - name: templateName
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Template status fetched
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'

  /v1/get-template:
    get:
      summary: Get templates with filters
      parameters:
        - name: botId
          in: query
          schema:
            type: string
        - name: templateType
          in: query
          schema:
            type: string
        - name: templateName
          in: query
          schema:
            type: string
        - name: status
          in: query
          schema:
            type: string
        - name: pageSize
          in: query
          schema:
            type: integer
        - name: currentPage
          in: query
          schema:
            type: integer
      responses:
        '200':
          description: Templates fetched successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'

  /v1/get-templateId-by-templateName-and-botId:
    get:
      summary: Get templateId by templateName and botId
      parameters:
        - name: templateName
          in: query
          required: true
          schema:
            type: string
        - name: botId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: TemplateId fetched
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
