openapi: 3.0.3
info:
  title: Pinnacle Api Documentation
  description: >
    Pinnacle Teleservices Pvt. Ltd. offers digital communication solutions,
    focusing on automated, omnichannel customer engagement through services
    like WhatsApp Business API, Google RCS, bulk SMS, IVR, and AI-powered
    chatbots. It helps businesses build strong customer relationships via
    personalized messaging, promotions, and customer support across multiple
    channels, backed by direct telecom connectivity for reliability,
    delivery tracking, and performance monitoring.
  version: 1.0.0

servers:
  - url: https://XXXXXX.pinnacle.com

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: apikey

  schemas:
    Image:
      type: object
      properties:
        url:
          type: string
        type:
          type: string
        key:
          type: string

    PhoneNumber:
      type: object
      properties:
        number:
          type: string
        label:
          type: string
        countryCode:
          type: string
        country:
          type: string

    Website:
      type: object
      properties:
        url:
          type: string
        label:
          type: string

    Email:
      type: object
      properties:
        email:
          type: string
        label:
          type: string

    Bot:
      type: object
      properties:
        _id:
          type: string
        orgId:
          type: string
        brandName:
          type: string
        brandId:
          type: string
        botName:
          type: string
        botType:
          type: string
        botMessageType:
          type: string
        botLogoImage:
          $ref: '#/components/schemas/Image'
        botBannerImage:
          $ref: '#/components/schemas/Image'
        shortDescription:
          type: string
        color:
          type: string
        phoneNumbers:
          type: array
          items:
            $ref: '#/components/schemas/PhoneNumber'
        websites:
          type: array
          items:
            $ref: '#/components/schemas/Website'
        emails:
          type: array
          items:
            $ref: '#/components/schemas/Email'
        termsofUseUrl:
          type: string
        privacyPolicyUrl:
          type: string
        developmentPlatform:
          type: string
        chatbotWebhook:
          type: string
        languagesSupported:
          type: string
        status:
          type: string
        templateIds:
          type: array
          items:
            type: string
        clientName:
          type: string
        testDevices:
          type: array
          items:
            type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

paths:

  /v1/get-botId-by-botName:
    get:
      summary: Get botId by botName
      description: Fetch botId using bot name
      security:
        - ApiKeyAuth: []
      parameters:
        - name: botName
          in: query
          required: true
          description: Name of bot
          schema:
            type: string
      responses:
        '200':
          description: BotId fetched successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  code:
                    type: integer
                  data:
                    type: object
                    properties:
                      message:
                        type: string
                      botName:
                        type: string
                      orgId:
                        type: string
                      botId:
                        type: string

  /v1/get-all-bots:
    get:
      summary: Get all bots
      description: Fetch all bots
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: All bots fetched
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  code:
                    type: integer
                  data:
                    type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/Bot'
                      message:
                        type: string

  /v1/get-all-launched-bots-by-orgId:
    get:
      summary: Get launched bots by orgId
      description: Fetch launched bots for an organization
      security:
        - ApiKeyAuth: []
      parameters:
        - name: orgId
          in: query
          required: true
          description: Organization ID
          schema:
            type: string
      responses:
        '200':
          description: Launched bots fetched
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  code:
                    type: integer
                  data:
                    type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/Bot'
                      message:
                        type: string

  /v1/get-bot-details/{botId}:
    get:
      summary: Get bot details by botId
      description: Fetch detailed bot information
      security:
        - ApiKeyAuth: []
      parameters:
        - name: botId
          in: path
          required: true
          description: Bot ID
          schema:
            type: string
      responses:
        '200':
          description: Bot details fetched
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  code:
                    type: integer
                  data:
                    $ref: '#/components/schemas/Bot'
